version: '3.7'
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todoapp
    command: postgres

  nodejs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_started
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: todoapp
      PGUSER: postgres
      PGPASSWORD: admin
    command: node .
